In [8]:
import numpy as np
from pyDatalog import pyDatalog
from pyDatalog import pyEngine

def maxP(x, y):
    z = []
    for x1 in x:
        for y1 in y.T:
            z.append(max(np.multiply(x1, y1)))
    return np.array(z).reshape((x.shape[0], y.shape[1]))

arr1 = np.array  ([[0, 0.2, 0.7, 0.8],
               [0, 0.3, 0.7, 0.5], 
               [0.5, 0.5, 0.5, 0.5],
               [0.7, 0.4, 0.4, 0.6], 
               [0.7, 0.7, 0.3, 0.3]])

arr2 = np.array  ([[0, 0.3, 0.3, 0.7, 0],
               [0.3, 0.1, 0.7, 0.3, 0.8],
               [0.8, 0.6, 0.5, 0.4, 0.3], 
               [0.8, 0.8, 0.5, 0.6, 0.2]])

print("Колдуны")
print(arr1)
print("\n")
print("Волшебники")
print(arr2)
print("\n")
print("Cтроки(колдуны) и столбцы(волшебники)")
print(maxP(arr1, arr2))

Колдуны
[[ 0.   0.2  0.7  0.8]
 [ 0.   0.3  0.7  0.5]
 [ 0.5  0.5  0.5  0.5]
 [ 0.7  0.4  0.4  0.6]
 [ 0.7  0.7  0.3  0.3]]


Волшебники
[[ 0.   0.3  0.3  0.7  0. ]
 [ 0.3  0.1  0.7  0.3  0.8]
 [ 0.8  0.6  0.5  0.4  0.3]
 [ 0.8  0.8  0.5  0.6  0.2]]


Cтроки(колдуны) и столбцы(волшебники)
[[ 0.64  0.64  0.4   0.48  0.21]
 [ 0.56  0.42  0.35  0.3   0.24]
 [ 0.4   0.4   0.35  0.35  0.4 ]
 [ 0.48  0.48  0.3   0.49  0.32]
 [ 0.24  0.24  0.49  0.49  0.56]]


In [ ]:
1 Титан vs Костяной дракон
2 Феи vs Ведьмы
3 Рыцарей vs Вампиров
5 Крестьяне vs Зомби
8 Эльфов vs Скелеты

Всего: 2610 